###########################################################
## Global Values
###########################################################

homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude

  unit_system: imperial
  time_zone: America/Chicago

  name: Apartment

  ###########################################################
  ## Customization Config
  ###########################################################

  customize: !include customize.yaml

###########################################################
## API & Web UI Password
###########################################################

http:
  api_password: !secret http_password

###########################################################
## LiFX Config
###########################################################

light:
  platform: lifx
  broadcast: 10.0.1.255

###########################################################
## IFTTT Config
###########################################################

ifttt:
  key: !secret ifttt_key

###########################################################
## Google Config
###########################################################

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

###########################################################
## MQTT Config (move to locally hosted server)
###########################################################

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass

###########################################################
## Device Tracker Conig
###########################################################

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

  - platform: nmap_tracker
    hosts: 10.0.1.1/24

###########################################################
## Z-Wave Config
###########################################################

zwave:
  usb_path: /dev/ttyACM0
  config_path: /usr/local/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-x86_64.egg/config

###########################################################
## UPS Config 
###########################################################

apcupsd:
  host: 127.0.0.1
  port: 3551

###########################################################
## Roku Config
###########################################################

media_player:
  - platform: roku
    host: 10.0.1.191

###########################################################
## Emulated Hue for Alexa
###########################################################

emulated_hue:
  host_ip: 10.0.1.4
  expose_by_default: false

###########################################################
## Groups, Senors, Automations, Inputs, Scripts, Switches
###########################################################

automation: !include automations.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_slider: !include input_slider.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
alexa: !include alexa.yaml
panel_iframe: !include panel_iframe.yaml

###########################################################
## Other Stuff
###########################################################

recorder:
history:
logbook:
sun:
discovery:
